# Generated by Django 5.0 on 2024-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('starting_price', models.CharField(max_length=100)),
                ('category', models.TextField(choices=[('Dining', 'Dining'), ('Health', 'Health'), ('Leisure', 'Leisure')])),
            ],
        ),
    ]
