# Generated by Django 5.0 on 2024-02-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_serviceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
